Flask practice homework
vadiq/common pull request #10
Opened 2019-10-29 19:29 UTC by vadiq

2019-10-31 14:53 UTC, dimigor requested changes

2019-10-31 14:53 UTC, dimigor commented on flask_lesson_intro/main.py
> +    return render_template("author.html", title='Author')
try to make universal route

2019-10-31 14:53 UTC, dimigor commented on flask_lesson_intro/templates/author.html
> +{% endblock content %}
missed endline and tabulation

2019-10-31 14:53 UTC, dimigor commented on flask_lesson_intro/templates/home.html
> +        <area href="/headphones" coords="392,143,242,11" shape="rect">
use `url_for` instead

2019-10-31 14:53 UTC, dimigor commented on flask_lesson_intro/templates/layout.html
> +    <style>
for styles create file `styles.css`

2019-10-31 14:53 UTC, dimigor commented on flask_lesson_intro/utils.py
> +        return json.load(file)
what if file will not found?

2019-10-31 18:27 UTC, vadiq commented on flask_lesson_intro/utils.py
> +        return json.load(file)
if file will not be found - then some of my app pages will be lacking of some info

2019-11-01 08:02 UTC, dimigor requested changes

2019-11-01 08:02 UTC, dimigor commented on flask_lesson_intro/templates/layout-items.html
> +        {% if element.title == item %}
maybe you should do this logic at the route?

2019-11-01 10:40 UTC, dimigor approved these changes

2019-11-01 11:22 UTC, merged