flask-3 homework finished!
vadiq/common pull request #12
Opened 2019-11-06 14:11 UTC by vadiq

2019-11-08 21:16 UTC, yuriimchg requested changes
переглянув дз
виглядає дуже круто
окремий плюс за гарний дизайн і картинки, які завантажуються по дефолту
але є декілька зауважень:
* щоб запустити апку мені довелося трошки модифікувати імпорти. Інакше вона просто не запускалася
* продукти не можуть мати від'ємної або текстової ціни і це неймовірно тішить. Але також вони не можуть коштувати не ціле значення 
* після того, як клікнув 1 раз по продукту, більше по ньому не можу клікнути. Це баг чи фіча? До речі, по id можу потім достукатися
* лінтер свариться на купу всього
* No newline at the end of file
* Також можу додати супермаркети без розміщення (не впевнений, що це не ок, але напишу, щоб ти був вкурсі про це)
* Також, здається, мала бути якась фільтрація продуктів / супермаркетів

2019-11-08 21:16 UTC, yuriimchg commented on flask_3/supermarkets/main.py
> +from .forms import AddSupermarketForm
лайк за імпорти по пепу

2019-11-09 09:44 UTC, vadiq commented on flask_3/supermarkets/main.py
> +from .forms import AddSupermarketForm
;)

2019-11-09 10:30 UTC, vadiq commented
> щоб запустити апку мені довелося трошки модифікувати імпорти. Інакше вона просто не запускалася

поправив
> No newline at the end of file

поправив

> продукти не можуть мати від'ємної або текстової ціни і це неймовірно тішить. Але також вони не можуть коштувати не ціле значення

поправив

> після того, як клікнув 1 раз по продукту, більше по ньому не можу клікнути. Це баг чи фіча? До речі, по id можу потім достукатися

це фіча по ТЗ

> лінтер свариться на купу всього

мій пайлінт не читає хтмл-шаблони, але індентацію всюди зроблено;
також він здебільшого каже про докстрінги для класів і методів, і довжину рядків 100 знаків, але також каже щоб константи як-от назва блупрінтів були написані капсом, хоча ми в лекціях цього не писали, і ніде на ютубі такого не зустрічав

> Також можу додати супермаркети без розміщення (не впевнений, що це не ок, але напишу, щоб ти був вкурсі про це)
я в курсі, я не робив це поле обов'язковим навмисно, тільки назву супермаркета. про обов'язковість в ТЗ не написано)

> Також, здається, мала бути якась фільтрація продуктів / супермаркетів
це реалізовано, але на рівні параметрів в урлі

2019-11-11 22:30 UTC, yuriimchg requested changes
отримав 500 респонс, коли спробував додати картинку до їжі чи супермаркета:
![image](https://user-images.githubusercontent.com/33547678/68625572-23ebd700-04e2-11ea-8033-2a40855354d8.png)

лінтер вже не свариться. До речі, flake8 реагує лише на `*.py` файли, інші ігнорує
також мені не вдалося запустити напряму апку, лише через `flask_run`. Якщо ти планував так з самого початку, то створи `README.md` і опиши, що треба зробити, щоб запустити апку.
Також нагадую, що можна вдосконалити код, додавши type hints

тут є трохи ~~хороших~~ прикладів:
https://github.com/puckel/docker-airflow
https://github.com/yuriimchg/stream_video 


все інше виглядає дуже ок

2019-11-11 22:30 UTC, yuriimchg commented on flask_3/products/main.py
> +                    products_filter.append(item)
можливо, цей кусок можна трохи оптимізувати :wink:

2019-12-07 19:43 UTC, vadiq commented on flask_3/products/main.py
> +                    products_filter.append(item)
зробив рефакторинг

2019-12-15 22:07 UTC, yuriimchg approved these changes
переглянув, все ок :+1: 
з зауважень - можна ще пофіксити фото супермаркетів

2019-12-16 08:46 UTC, merged