finished homework
vadiq/common pull request #3
Opened 2019-09-30 08:13 UTC by vadiq

2019-10-01 19:33 UTC, yuriimchg requested changes
привіт
перевірив твою роботу
виглядає дуже класно, сподобалося, що запити не всі в один рядок)
+++ за уважність до деталей
але є деякі нюанси
по-перше,  впали два тести, які не мали падати
по-друге, PEP-8:

```
>>> flake8 homework.py

homework.py:21:30: W291 trailing whitespace
homework.py:22:80: E501 line too long (84 > 79 characters)
homework.py:38:17: W291 trailing whitespace
homework.py:54:17: W291 trailing whitespace
homework.py:55:23: W291 trailing whitespace
homework.py:72:25: W291 trailing whitespace
homework.py:73:39: W291 trailing whitespace
homework.py:88:30: W291 trailing whitespace
homework.py:89:25: W291 trailing whitespace
homework.py:90:35: W291 trailing whitespace
homework.py:107:23: W291 trailing whitespace
homework.py:124:23: W291 trailing whitespace
homework.py:125:23: W291 trailing whitespace
homework.py:152:80: E501 line too long (101 > 79 characters)
homework.py:160:42: W291 trailing whitespace
homework.py:161:23: W291 trailing whitespace
homework.py:162:25: W291 trailing whitespace
homework.py:163:38: W291 trailing whitespace
homework.py:175:17: W291 trailing whitespace
homework.py:176:23: W291 trailing whitespace
homework.py:192:17: W291 trailing whitespace
homework.py:193:23: W291 trailing whitespace
homework.py:210:23: W291 trailing whitespace
homework.py:226:27: W291 trailing whitespace
homework.py:227:22: W291 trailing whitespace
homework.py:228:29: W291 trailing whitespace
homework.py:229:54: W291 trailing whitespace
homework.py:246:22: W291 trailing whitespace
homework.py:247:29: W291 trailing whitespace
homework.py:248:54: W291 trailing whitespace
homework.py:263:59: W291 trailing whitespace
homework.py:264:23: W291 trailing whitespace
homework.py:265:26: W291 trailing whitespace
homework.py:281:80: E501 line too long (85 > 79 characters)
homework.py:281:86: W291 trailing whitespace
homework.py:282:63: W291 trailing whitespace
homework.py:283:23: W291 trailing whitespace
homework.py:284:28: W291 trailing whitespace
homework.py:285:49: W291 trailing whitespace

```

про задовгі рядки: якщо вважаєш, що розбивання рядка на два менші рядки погіршує читабельність коду, то краще нехай рядок буде довшим і більш читабельним, ніж коротким

2019-10-01 19:33 UTC, yuriimchg commented on relational_database/homework.py
> +        con: psycopg cursor
```suggestion
        con: psycopg connection object
```

взагалі дуже круто, що ти помітив помилку в описі :wink: :+1:

2019-10-01 19:33 UTC, yuriimchg commented on relational_database/homework.py
> +        """)
тут впав тест
ймовірно, не з того кастомера почав рахувати

2019-10-01 19:33 UTC, yuriimchg commented on relational_database/homework.py
> +        """)
На цьому завданні також впав тест. Зразок твого рядка:
`{'supplierid': 1, 'suppliername': 'Exotic Liquid', 'contactname': 'Charlotte Cooper', 'address': '49 Gilbert St.', 'city': 'Londona', 'postalcode': 'EC1 4SD', 'country': 'UK', 'phone': '(171) 555-2222'}`
Зразок рядка в тестах:
`{'supplierid': 1, 'suppliername': 'Exotic Liquid', 'contactname': 'Charlotte Cooper', 'city': 'Londona', 'country': 'UK'}`

2019-10-01 19:33 UTC, yuriimchg commented on relational_database/homework.py
> +        """)
перевір, будь ласка, чи в тебе тести тут не падають

2019-10-01 19:41 UTC, vadiq commented on relational_database/homework.py
> +        con: psycopg cursor
точняк) спс

2019-10-01 19:46 UTC, vadiq commented on relational_database/homework.py
> +        """)
хм, на w3schools все як потрібно. тут же відбір піде по values в CustomerId, і тому мало б працювати, навіть якщо порядок був інший, чи я помиляюсь

2019-10-01 20:03 UTC, vadiq commented on relational_database/homework.py
> +        """)
даний тест фейлиться, тому що він хоче свій набір колонок (хоча про це в умові не написано). є необхідність все-таки вказати в селект колонки і зробити новий коміт?

2019-10-01 20:06 UTC, vadiq commented on relational_database/homework.py
> +        """)
аа, я згадав - це тест падає, тому що в перевірочному json-файлі набір даних починається з 12 елемента, а не з 11. я його додавав в json-файл, щоб виконати умову завдання

2019-10-01 20:13 UTC, vadiq commented
стосовно задовгих рядків - мені пайчарм нічого не повідомляв, що вказані тобою рядки задовгі. в мене були справді задовгі рядки, як наприклад рядок 281, який я розбивав.
до РЕР-8 я ще не дійшов)) в моєму пайчарм очевидно встановлена позначка на 120 символів

2019-10-02 06:50 UTC, yuriimchg commented on relational_database/homework.py
> +        """)
так

2019-10-02 06:51 UTC, yuriimchg commented on relational_database/homework.py
> +        """)
> стосовно задовгих рядків - мені пайчарм нічого не повідомляв, що вказані тобою рядки задовгі. в мене були справді задовгі рядки, як наприклад рядок 281, який я розбивав.
> до РЕР-8 я ще не дійшов)) в моєму пайчарм очевидно встановлена позначка на 120 символів

до PEP-8 варто звикати з самого початку - тому й стільки питань стосовно цього :wink: 
і так, зазвичай пайшарм починає сваритися, коли довжина рядка перевалює аж за 120

2019-10-02 08:49 UTC, yuriimchg approved these changes

2019-10-02 08:50 UTC, merged