tests_homework is finished!
vadiq/common pull request #6
Opened 2019-10-16 07:28 UTC by vadiq

2019-10-17 06:14 UTC, yuriimchg requested changes
:heavy_plus_sign:   не полінувався почитати про mock. 
:heavy_plus_sign: лінтер не свариться (крім докстрінги, яку додали викладачі)
:heavy_minus_sign:  немає[ type hints](https://docs.python.org/3.7/library/typing.html). Це не є обов'язково, але значно підвищує читабельність коду. Старайся додавати їх за можливості.
:heavy_minus_sign: дуже страждає неймінг. Старайся не називати змінні `a`, `c` чи якось схоже, коли їх можна позначити як `array`, `check_list` чи шось таке. Також не ітеруй по змінній `i`, якщо вона не є цілим числом - це, хоч і не є помилкою, але є дуже поганою практикою, оскільки підсвідомо змушує думати, що `isinstance(i, int) == True`, хоча це насправді не так.
:heavy_minus_sign: старайся не використовувати метод `input()`, якщо завдання цього прямо не вимагає - завжди є більш цивілізовані методи вводу, ніж кожного разу з клавіатури
:heavy_minus_sign: не потрібно створювати різні тесткейси в одному тесті, краще створити один тест для assertTrue, інший для assertFalse


Крім того в коді старайся більше використовувати більше вбудованих методів. [PEP8](https://www.python.org/dev/peps/pep-0008/) каже, що потрібно надавати перевагу більш високорівневим методам хоча б тому, що вони зазвичай краще працюють + протестовані ( _це зауваження більше стосується коду в проді, але воно спрацює і для 1, 5, 7, 8, 13, 16 завдань_ )

Крім того[2]: не потрібно робити стільки перевірок типів, оскільки дуже багато невалідних даних відваляться самостійно. Якщо сумніваєшся, що список зможе пройти там, де очікується `int`, спробуй запустити його туди. Скоріше за все підніметься TypeError - а це значно краще, ніж захардкоджений ValueError без жодного повідомлення, де і що впало. Також не потрібно стільки перевірок на те, чи порожній список / рядок - якщо він порожній, то ітерація по ньому матиме нуль циклів і все.


Крім того[3]: дуже раджу почитати книжку Роберта Мартіна `Clean Code` (хоч там і приклади на Java) або (ця мені більше зайшла) Code Complete Стіва Макконела. Там ці всі випадки описані дуже добре.

Крім того[4]: Дуже рекомендую почитати щось про юніттести. Хоча б якусь статтю, наприклад цю: https://realpython.com/python-testing/ (не така велика, як здається)

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +    if not c:
для чого ти повертаєш `None`, коли список порожній?
хіба не краще повертати об'єкт того самого типу, який очікується?

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +    while num > power:
дуже цікаве рішення
_+_ завжди спрацює для цілих чисел

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +    return sum(a) == arithmetic_sequence_sum
рішення дуже круте,
але не впевнений, що спрацює двосторонньо
тобто сума арифметичної прогресії завжди буде дорівнювати [цьому](url
![image](https://user-images.githubusercontent.com/33547678/66979844-a20db700-f0b7-11e9-91d2-9b731a1e794c.png)

але не завжди з суми можна отримати арифметичну прогресію.
Наприклад:

![image](https://user-images.githubusercontent.com/33547678/66979998-23fde000-f0b8-11e9-80d5-d67cd8cab322.png)

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +    for i in a:
тут (і не лише тут) не варто використовувати змінну `i` для ітерації, якщо ітеруєш не по цілочисельній змінній

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +    for i in a:
також тут має сенс використання вбудованої функції `enumerate`

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +    # return "".join(a)
`first attempt` досить непогана, але не є потрібною, оскільки код працює без неї)

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +    if type(text) is str:  # check if type is string and not empty
не змушую виправляти, але радив би переглянути)
https://stackoverflow.com/questions/1549801/what-are-the-differences-between-type-and-isinstance

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +    raise ValueError
для кращого розуміння, чому тут має піднятися ValueError все ж краще додати `else` чи щось таке, бо не дуже очевидно, чому він саме тут має піднятися.
Хоча у випадку з `return` все було б ок

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +    num = int(input('Enter item counts for Fibonacci numbers\n'))
не думаю, що використання функції `input` є хорошим рішенням

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +    num = int(input('Enter item counts for Fibonacci numbers\n'))
краще взяти змінну як вхідний аргумент

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +        if a:  # check if list is not empty
навіть, якщо `a == []`, цієї перевірки не потрібно (в завданнях вище є схожі зауваження) - у випадку порожнього списку функція повернеться в 253 рядку

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +    if type(a) is list:  # check if variable is list
чому `a` не може бути `tuple` чи `numpy.ndarray`?

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +        if a:  # check if list is not empty
також йдеться про `one line of Python`

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +    if type(a) is list:  # check if variable is list
чи іншого `iterable` типу?

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/definitions.py
> +    raise ValueError
також не треба ValueError
він ловить тільки тьюпли і стрінги
причому на стрінгах все одно впаде код на 249 рядку

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/unittests.py
> +            ('good developer', 0)
:sunglasses:

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/unittests.py
> +                self.assertTrue(task3_is_power(i))
думаю, ці два тесткейси можна розбити на 2 різні тести

2019-10-17 06:14 UTC, yuriimchg commented on tests_practice/unittests.py
> +        a1 = [14, 15, 16, 17]
тут краще розбити на різні тесткейси

2019-10-17 08:18 UTC, vadiq commented on tests_practice/definitions.py
> +    while num > power:
сам в шоці, що додумався до цього)

2019-10-17 08:18 UTC, vadiq commented on tests_practice/definitions.py
> +    return sum(a) == arithmetic_sequence_sum
ти правий, якщо змінити порядок елементів - то не має працювати, але через суму працюватиме.
перепишу метод

2019-10-17 08:18 UTC, vadiq commented on tests_practice/definitions.py
> +    raise ValueError
тобто варто додавати `else`, щоб було очевидно - explicit, і все таке?

2019-10-17 08:18 UTC, vadiq commented on tests_practice/definitions.py
> +    num = int(input('Enter item counts for Fibonacci numbers\n'))
так в задачі ж сказано 

> asks the user how many Fibonacci numbers to generate

2019-10-17 08:18 UTC, vadiq commented on tests_practice/definitions.py
> +    raise ValueError
а хіба перевірка на 247 рядку не відфільтрує лишні типи?

2019-10-17 08:18 UTC, vadiq commented on tests_practice/unittests.py
> +        a1 = [14, 15, 16, 17]
ок, зробим. на майбутнє - якщо відбувається інша умова перевірки в тесті - то варто виносити в окремий тесткейс?

2019-10-17 08:18 UTC, vadiq commented on tests_practice/unittests.py
> +            ('good developer', 0)
😁

2019-10-17 08:18 UTC, vadiq commented on tests_practice/unittests.py
> +                self.assertTrue(task3_is_power(i))
ok

2019-10-17 08:25 UTC, vadiq commented on tests_practice/definitions.py
> +    if not c:
я про це думав, коли писав перевірки на аутпут.
в нашій домашці - не зрозуміло, який аутпут вимагається при неочікуваному результаті. все ж залежить від потреби в подальших етапах - може треба об'єкт того самого типу, а може потрібно `None` - я вибрав останнє, бо вважаю це більш прийнятним в даній домашці. хоча простіше було б об'єкт того самого типу, бо не потрібно було б лишні перевірки для аутпута писати 😏

2019-10-17 08:28 UTC, vadiq commented on tests_practice/definitions.py
> +    # return "".join(a)
💪

2019-10-17 08:29 UTC, vadiq commented on tests_practice/definitions.py
> +    for i in a:
ок, врахую, перепишу

2019-10-17 08:30 UTC, vadiq commented on tests_practice/definitions.py
> +    if type(text) is str:  # check if type is string and not empty
мені пайлінт підказував, що краще через ізінстанс перевірку типу робити.
перепишу

2019-10-17 08:46 UTC, vadiq commented on tests_practice/definitions.py
> +    if type(a) is list:  # check if variable is list
я розцінив 

> I give you a list

як беззаперечну умову. якісь перевірки ж треба було писати в будь-якому разі, чи не так?)

2019-10-17 08:46 UTC, vadiq commented on tests_practice/definitions.py
> +        if a:  # check if list is not empty
> у випадку порожнього списку функція повернеться в 253 рядку

згоден. приберу
> one line of Python

по суті я зробив в одну строку, решта строк - це перевірки

2019-10-17 21:47 UTC, yuriimchg reviewed
переглянув, ще є деяі зауваження

2019-10-17 21:47 UTC, yuriimchg commented on tests_practice/definitions.py
> +        raise TypeError
цього не треба)
TypeError і без цього підніметься)

2019-10-17 21:47 UTC, yuriimchg commented on tests_practice/definitions.py
> +    result = str(hour) + ':' + str(minute)
спробуй тут використати форматування стрічок
https://realpython.com/python-f-strings/

2019-10-17 21:47 UTC, yuriimchg commented on tests_practice/definitions.py
> +    if isinstance(lst, list) and lst:  # check if list and is not empty
тут (і в попередніх аналогічних перевірках) логічніше перевіряти спочатку, чи змінна не порожня і вже тоді перевіряти, якого вона типу)

2019-10-17 21:47 UTC, yuriimchg commented on tests_practice/definitions.py
> +    if isinstance(num, int):
тут не обов'язкова перевірка, бо range() не прийме float значення

2019-10-17 22:25 UTC, yuriimchg reviewed
тести: загалом ок, але в тебе тесткейси, які піднімають помилки, дуже вибіркові. Наприклад, є ` task12_largest_word(59)`, але ти не перевіряєш порожню стрічку чи щось більш реальне. Також побачив, що ближче до кінця падаючі тесткейси стають більш реальними)

2019-10-17 22:25 UTC, yuriimchg commented on tests_practice/unittests.py
> +            with self.subTest(elem=elem):
```suggestion
            with self.subTest(i=elem):
```
інакше не запуститься сабтест

2019-10-17 22:25 UTC, yuriimchg commented on tests_practice/pytests.py
> +@pytest.mark.parametrize("give_input, result",
`test_input` було б кращим іменем для вхідних даних в тесті, ніж `give_input`

2019-10-17 22:25 UTC, yuriimchg commented on tests_practice/pytests.py
> +    with patch('builtins.input', return_value='give_input'):
а тут якраз класно було б напхати хоча б декілька від'ємних, флоатів, двійкових чисел ітд)

2019-10-17 22:25 UTC, yuriimchg commented on tests_practice/unittests.py
> +            with self.subTest(elem=elem):
ну і в наступних тестах аналогічно

2019-10-22 21:07 UTC, yuriimchg requested changes
привіт
мушу ще раз змусити тебе переробити дз
перевір пайтести - вони падають. Юніттести не падають)
ще
в 6 завданні не потрібно `i += 1`
воно й так інкрементує на 1 в циклі
також я би все ж додав `else` в 15, 19, 20, 12 і 13 завданнях перед тим, як викидати ValueError, але це на твій розсуд

2019-10-22 21:07 UTC, yuriimchg commented on tests_practice/definitions.py
> +    return f'{str(hour)}:{str(minute)}'
не обов'язково конвертувати число в стрінгу - за тебе це зробить форматування коду)

2019-10-22 21:07 UTC, yuriimchg commented on tests_practice/definitions.py
> +    raise ValueError
так
explicit is better than implicit

2019-10-25 12:40 UTC, dimigor approved these changes

2019-10-29 09:04 UTC, merged